<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Notify from {appName}. You were added to the group.' => 'تنبيه من {appName}. تمت إضافتك للمجموعة.',
    'Notify from {appName}. You were removed from the group.' => 'تنبيه من {appName}. تمت إزالتك من المجموعة.',
    'There is a new HumHub Version ({version}) available.' => 'تتوفر نسخة جديدة من هوم-هوب - نسخة رقم {version}.',
    '{displayName} added you to group {groupName}' => 'قام {displayName} بإضافتك للمجموعة {groupName}',
    '{displayName} removed you from group {groupName}' => 'قام {displayName} بإزالتك من المجموعة {groupName}',
];
