<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access Admin Information' => 'الوصول لمعلومات المدير',
    'Can access the \'Administration -> Information\' section.' => 'يستطيع الوصول إلى (لوحة التحكم > الساحات) إنشاء/تعديل/حذف',
    'Can manage spaces within the \'Administration -> Spaces\' section (create/edit/delete).' => 'يستطيع إدارة الساحات عبر (لوحة التحكم > الساحات) إنشاء/تعديل/حذف',
    'Can manage user- space- and general-settings.' => 'يستطيع إدارة المستخدم-الساحة- و الإعدادات العامة',
    'Can manage users and groups' => 'يستطيع إدارة المستخدمين والمجموعات',
    'Can manage users and user profiles.' => 'يستطيع إدارة المستخدمين وملفات المستخدمين الشخصية',
    'Can manage modules within the \'Administration ->  Modules\' section.' => 'يستطيع إدارة الموديولات عبر (لوحة التحكم > الموديولات)',
    'Manage Groups' => 'إدارة المجموعات',
    'Manage Modules' => 'إدارة الموديولات',
    'Manage Settings' => 'إدارة الإعدادات',
    'Manage Spaces' => 'إدارة الساحات',
    'Manage Users' => 'إدارة المستخدمين',
];
