<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advanced Settings' => 'إعدادات متقدمة',
    'Appearance Settings' => 'إعدادات المظهر',
    'General Settings' => 'إعدادات عامة',
    'Here you can configurate the registration behaviour and additinal user settings of your social network.' => 'تستطيع ضبط إعدادات نمط التسجيل وإعدادات الأعضاء الأخرى لشبكتك من هنا.',
    'Here you can configure basic settings of your social network.' => 'تستطيع ضبط الإعدادات الأساسية لشبكتك الإجتماعية من هنا.',
    'Notification Settings' => 'إعدادات التنبيهات',
    'These settings refer to advanced topics of your social network.' => 'هذه الإعدادات تختص بمواضيع متقدمة في شبكتك الإجتماعية.',
    'These settings refer to the appearance of your social network.' => 'هذه الإعدادات تختص بمظهر شبكتك الإجتماعية.',
    'User Settings' => 'إعدادات المستخدم',
    'General' => 'عام',
    'LDAP' => 'LDAP',
];
