<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Information</strong>' => '<strong>معلومات</strong>',
    '<strong>Settings</strong> and Configuration' => '<strong>الإعدادات</strong> والضبط',
    '<strong>User</strong> administration' => '<strong>إدارة</strong> المستخدمين',
    'Active users' => 'المستخدمين النشطين',
    'Add new group' => 'إضافة مجموعة جديدة',
    'Add new user' => 'إضافة مستخدم جديد',
    'Are you really sure that you want to disable this user?' => 'هل أنت متأكد من رغبتك في إيقاف هذا المستخدم؟',
    'Are you really sure that you want to enable this user?' => 'هل أنت متأكد من رغبتك في تفعيل هذا المستخدم؟',
    'Are you really sure that you want to impersonate this user?' => 'هل أنت متأكد من رغبتك في انتحال هذا المستخدم؟',
    'Are you sure that you want to delete following user?' => 'هل أنت متأكد من رغبتك في حذف المستخدم التالي؟',
    'Cancel' => 'إلغاء',
    'Confirm user deletion' => 'تأكيد حذف المستخدم',
    'Delete all contributions of this user' => 'حذف جميع مساهمات هذا المستخدم',
    'Delete spaces which are owned by this user' => 'حذف الساحات المملوكة من قبل هذا المستخدم',
    'Deleted users' => 'حذف المستخدمين',
    'Disable' => 'تعطيل',
    'Disabled users' => 'تعطيل المستخدمين',
    'Enable' => 'تفعيل',
    'Group Manager' => 'مدير المجموعة',
    'If this option is not selected, the ownership of the spaces will be transferred to your account.' => 'إذا لم تحدد هذا الخيار، ستنتقل ملكية الساحات إلى حسابك.',
    'Impersonate' => 'انتحال',
    'Last login' => 'آخر دخول',
    'List pending registrations' => 'قائمة طلبات التسجيل المعلقة',
    'Manage group: {groupName}' => 'إدارة المجموعة: {groupName}',
    'Member since' => 'عضو منذ',
    'Members' => 'الأعضاء',
    'Pending approvals' => 'في انتظار الموافقة',
    'Permanently delete' => 'حذف نهائي',
    'Permissions' => 'الصلاحيات',
    'Profiles' => 'الملفات الشخصية',
    'Search by name, email or id.' => 'البحث باسم المستخدم أوالإيميل أو الإسم الكامل',
    'Settings' => 'الإعدادات',
    'This overview contains a list of each registered user with actions to view, edit and delete users.' => 'هذه النظرة العامة تحوي قائمة الأعضاء المسجلين، ما يمكنك من عرضهم أو التعديل أو الحذف.',
    'User deletion process queued.' => 'حذف المستخدم قيد الإنتظار',
    'Using this option any contributions (e.g. contents, comments or likes) of this user will be irrevocably deleted.' => 'عند تعيين هذا الخيار، كل مساهمات المستخدم سوف يتم حذفها نهائياً ولن تتمكن من استعادتها، من إعجاب وتعليقات ومحتويات منشورة.',
    'View profile' => 'عرض الملف الشخصي',
    'You cannot delete yourself!' => 'لا يمكنك حذف عضويتك!',
    'never' => 'مطلقاً',
    'Groups' => 'المجموعات',
    'Overview' => 'نظرة عامة',
];
