<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> image deletion' => '<strong>تأكيد</strong> حذف الصورة',
    'E.g. http://example.com/humhub' => 'على سبيل المثال: http:example.com/humhub',
    'Friendship' => 'الصداقة',
    'New users will automatically be added to these space(s).' => 'المستخدمون الجدد ستتم إضافتهم لهذه الساحة/الساحات تلقائياً.',
    'Wall entry layout' => 'أسلوب جدار الكتابة',
    'You\'re using no logo at the moment. Upload your logo now.' => 'يبدو أنك لا تستخدم شعاراً لشبكتك حالياً، قم برفع الشعار الآن.',
    'Dashboard' => 'الرئيسية',
    'Delete' => 'حذف',
    'Save' => 'حفظ',
];
