<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Do not change placeholders like {displayName} if you want them to be automatically filled by the system. To reset the email content fields with the system default, leave them empty.' => 'لا تقم بتغيير معين القيمة (placeholders) مثل {displayName} إذا كنت ترغب من النظام تعبئتهم تلقائياً. لتعيين محتوى حقول البريد الإلكتروني تلقائياً من النظام، اترك الحقول فارغة.',
    'Min value is 20 seconds. If not set, session will timeout after 1400 seconds (24 minutes) regardless of activity (default session timeout)' => 'أقل قيمة هي 20 ثانية. إذا لم يتم تعيين أي قيمة، سيتم تلقائياً إنهاء الجلسة بعد 1400 ثانية (24 دقيقة) بغض النظر عن الفعالية (إنهاء الجلسة افتراضياً).',
    'Only applicable when limited access for non-authenticated users is enabled. Only affects new users.' => 'قابل للتطبيق فقط عندما يكون الوصول للمستخدمين الغير المصرح مقيد ومفعل، سيؤثر فقط على المستخدمين الجدد.',
    'Visible for members only' => 'ظاهر للمستخدمين فقط',
    'Visible for members+guests' => 'ظاهر للمستخدمين والزوار',
    'General' => 'العام',
    'LDAP' => 'LDAP',
    'Save' => 'حفظ',
];
