<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comma separated list. Leave empty to allow all.' => 'قائمة بفاصلة للمتعدد. اتركه خالياً لتسمح للجميع.',
    'Current Image Library: {currentImageLibrary}' => 'مكتبة الصور الحالية: {currentImageLibrary}',
    'If not set, height will default to 200px.' => 'إذا لم تحدد هذا الخيار، سيتم تعيين الإرتفاع لـ 200 بكسل افتراضياً.',
    'If not set, width will default to 200px.' => 'إذا لم تحدد هذا الخيار، سيتم تعيين العرض لـ 200 بكسل افتراضياً.',
    'PHP reported a maximum of {maxUploadSize} MB' => 'أقصى حجم ممكن هو {maxUploadSize} ميقا بايت، حسب تقرير PHP',
    'Save' => 'حفظ',
];
