<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'HumHub is currently in debug mode. Disable it when running on production!' => 'يعمل هم-هوب الآن في وضع تصحيح الأخطاء. الرجاء تعطيل هذا الوضع عند العمل على وضع النسخة حية.',
    'See installation manual for more details.' => 'انظر دليل التثبيت لتفاصيل أكثر.',
    'Currently installed version: %currentVersion%' => 'النسخة المثبتة حالياً: %currentVersion%',
    'Licences' => 'التراخيص',
    'There is a new update available! (Latest version: %version%)' => 'هناك تحديث جديد متوفر! (النسخة الأخير: %version%)',
    'This HumHub installation is up to date!' => 'هذا التنصيب من هم-هوب هو الإصدار الأحدث!',
];
