<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Alphabetical' => 'أبجدي',
    'Auto format based on user language - Example: {example}' => 'تنسيق افتراضي حسب لغة المستخدم - على سبيل المثال: {example}',
    'Firstname Lastname (e.g. John Doe)' => 'الإسم الأول الإسم الأخير (مثل: John Doe)',
    'Fixed format (dd/mm/yyyy) - Example: {example}' => 'تنسيق ثابت (dd/mm/yyyy) - على سبيل المثال: {example}',
    'Last visit' => 'الزيارة الأخيرة',
    'Username (e.g. john)' => 'إسم المستخدم (مثل: John)',
    'Save' => 'حفظ',
];
