<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'Guest mode not active, please login first.' => 'وضع الزائر غير مفعل، الرجاء تسجيل الدخول.',
'Login required for this section.' => 'ينبغي تسجيل الدخول لعرض هذا القسم',
'You are not permitted to access this section.' => 'غير مسموح لك بالوصول لهذا القسم.',
'You need admin permissions to access this section.' => 'تحتاج لصلاحية مدير للوصول لهذا القسم.',
'Your user account has not been approved yet, please try again later or contact a network administrator.' => 'لم يتم تفعيل حسابك بعد، الرجاء المحاولة لاحقا أو التواصل مع الإدارة.',
'Your user account is inactive, please login with an active account or contact a network administrator.' => 'حسابك غير مفعل، الرجاء الدخول عبر حساب مفعل مسبقاً أو قم بالتواصل مع الإدارة.',
'<strong>Login</strong> required' => '<strong>الدخول</strong> مطلوب',
'An internal server error occurred.' => 'حصل خطأ داخلي في السيرفر.',
'You are not allowed to perform this action.' => 'غير مسموح لك بالقيام بهذا الإجراء.',
];
