<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
'<strong>E-Mail</strong> Summaries' => 'خلاصات <strong>البريد الإلكتروني</strong>',
'Activities' => 'الأنشطة',
'Daily' => 'يومي',
'E-Mail Summaries' => 'خلاصات البريد',
'E-Mail summaries are sent to inform you about recent activities in the network.' => 'يتم إرسال خلاصات البريد لإعلامك بالأنشطة الحالية في شبكتك.',
'E-Mail summaries are sent to users to inform them about recent activities in your network.' => 'يتم إرسال خلاصات البريد لإعلام المستخدمين بالأنشطة الحالية في شبكتك.',
'Exclude spaces below from the mail summary' => 'قم باستثناء المساحات في الأسفل من خلاصة البريد',
'Hourly' => 'كل ساعة',
'Interval' => 'فترة الخمول',
'Never' => 'مطلقاً',
'On this page you can configure the contents and the interval of these e-mail updates.' => 'يمكنك في هذه الصفحة تعيين المحتويات وفترات الإنتظار والخمول لتحديثات البريد الإلكتروني.',
'On this page you can define the default behavior for your users. These settings can be overwritten by users in their account settings page.' => 'يمكنك في هذه الصفحة تحديد الأسلوب الإفتراضي لمستخدميك. كما يمكن للمستخدمين التعديل على تلك الأساليب في صفحة إعدادات الحساب الخاصة بهم.',
'Only include spaces below to the mail summary' => 'قم بتعيين المساحات فقط أسفل الخلاصة البريدية',
'Reset to defaults' => 'تعيين الإفتراضي',
'Weekly' => 'أسبوعي',
'You will only receive an e-mail if there is something new.' => 'سنقوم بإرسال بريد إلكتروني في حال حصل أي شيء جديد.',
'Your weekly summary' => 'خلاصاتك الأسبوعية',
'Latest news' => 'آخر المستجدات',
'Spaces' => 'ساحات',
'Your daily summary' => 'خلاصاتك اليومية',
];
